---
name: CI
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  pull_request:
    branches: ["main"]  # Triggers on pull requests targeting the main branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  # Grouping by workflow name and reference
  cancel-in-progress: true  # Cancel any in-progress runs for the same group
env:
  MISE_EXPERIMENTAL: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Step 2: Install mise using the specified action
      - name: Install mise
        uses: jdx/mise-action@v2.2.2
      # Step 3: Run CI
      - name: Run CI
        run: mise ci
