---
name: CI
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  pull_request:
    branches: ["main"]  # Triggers on pull requests targeting the main branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  # Grouping by workflow name and reference
  cancel-in-progress: true  # Cancel any in-progress runs for the same group
env:
  MISE_EXPERIMENTAL: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      # Step 2: Install mise using the specified action
      - name: Install mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654  # v4.2.4
      # Step 3: Run CI
      - name: Run CI
        run: mise run ci
